version: "2"
services:
  angular-app:
    container_name: angular-app
    image: senanisammy@gmail.com/angular-app:1.0
    ports:
      - "5001:5001"

networks:
  default:
    external:
      name: staff-manager
