version: "2"
services:
  angular-app2:
    container_name: angular-app2
    image: sammmmmm/angular-app2:1.0
    ports:
      - "5001:80"

networks:
  default:
    external:
      name: staff-manager
