spring:
#  samlogy:
#    openapi:
#      dev-url: http://localhost:8080
  springdoc:
    api-docs:
      path: /bezkoder-api-docs
    packages-to-scan: com.bezkoder.spring.swagger.controller
    swagger-ui:
      filter: true
      operationsSorter: method
      path: /bezkoder-documentation
      tagsSorter: alpha
      tryItOutEnabled: true
  datasource:
    url: jdbc:postgresql://localhost:5432/demoapp
    username: postgres
    password: Postgres1618.
    driver-class-name: org.postgresql.Driver
  jpa:
    database-platform: org.hibernate.dialect.PostgreSQLDialect
    show-sql: true
    hibernate:
      ddl-auto: update
#  security:
#    user:
#      name: admin
#      password: admin
