spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/meetingPlanner
    username: postgres
    password: Postgres1618.
    driver-class-name: org.postgresql.Driver
  jpa:
    database-platform: org.hibernate.dialect.PostgreSQLDialect
    show-sql: true
    hibernate:
      ddl-auto: update
