spring:
  springdoc:
    api-docs:
      path: /samlogy-api-docs
    packages-to-scan: com.samlogy.spring.swagger.controller
    swagger-ui:
      filter: true
      operationsSorter: method
      path: /samlogy-documentation
      tagsSorter: alpha
      tryItOutEnabled: true
  datasource:
    url: jdbc:postgresql://localhost:5432/demoapp
    username: postgres
    password: Postgres1618.
    driver-class-name: org.postgresql.Driver
  jpa:
    database-platform: org.hibernate.dialect.PostgreSQLDialect
    show-sql: true
    hibernate:
      ddl-auto: update
  my:
    env:
      myEmail: senanisammy@gmail.com
#  flyway:
#    enabled: true
#    locations: classpath:db/migration
#    check-location: true
#    baselineOnMigrate: true
#    password: Postgres1618.
#    url: jdbc:postgresql://localhost:5432/demoapp
#    user: postgres

#  security:
#    user:
#      name: admin
#      password: admin
