name: CI/CD
on:
  push:
    branches:
      - "angular-github-actions"
jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Use Node.js
        uses: actions/setup-node@v1
        with:
          node-version: "18.x"

      - name: Run Npm
        run: npm i

      # - name: validations
      # - name: tests
      # - name: sonar

      - name: build
        run: npm run build

      - name: docker login
        env:
          DOCKER_USERNAME: ${{env.DOCKER_USERNAME}}
          DOCKER_PASSWORD: ${{env.DOCKER_PASSWORD}}
        run: docker login -u $DOCKER_USERNAME -p $DOCKER_PASSWORD
          docker build -t angular-app2 .
          docker tag angular-app2 $DOCKER_USERNAME/angular-app2:1.0
          docker push $DOCKER_USERNAME/angular-app2:1.0

    # - name: build and push docker image
    # run: |
    #   docker build -t angular-app2 .
    #   docker tag angular-app2 ${{secret.DOCKER_USERNAME}}/angular-app2:1.0
    #   docker push ${{secret.DOCKER_USERNAME}}/angular-app2:1.0
